# -*- coding: utf-8 -*-
"""옥션.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tn8AvIz9xWh72EXqz9a8tL1eJdendDBN
"""

import requests
from bs4 import  BeautifulSoup as bs
import pandas as pd

#1
url='http://corners.auction.co.kr/corner/categorybest.aspx?gender=0&age=0&storetab=0&cc='

response=requests.get(url)
b=[]
d=[]
f=[]
h=[]
if response.status_code==200:
  html=response.text
  soup=bs(html,'html.parser')
  a=soup.select('#itembest_T > ul > li > div > div.rank')
  for i in a:
    b.append(i.get_text())
  c=soup.select('#itembest_T > ul > li > div > div.info > em > a')
  for j in c:
    d.append(j.get_text())
    g=j.attrs['href']
    h.append(g)
  e=soup.select('#itembest_T > ul > li > div > div.info > ul > li.d_price > span.sale > span')
  for k in e:
    f.append(k.get_text())
else:
  print(response.status_code)

df=pd.DataFrame()
df['순위']=b
df['상품명']=d
df['가격']=f
df=df.set_index('순위')
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
print(df)